version: '3.9'
services:
  db:
    build: 
      context: .
      dockerfile: apps/postgres/Dockerfile
    image: openwork-api-db-image
    container_name: openwork-api-db-container
    restart: always
    ports:
      - 5433:5432
  
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: openwork-api-web-image
    container_name: openwork-api-web-container
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - db
    networks:
      - default
